"""Vision helpers for chat image analysis."""

import base64
import os

import google.generativeai as genai


def is_image_attachment(mime_type: str | None, file_base64: str | None) -> bool:
    """
    Helper function that evaluate if the message contains an image attached 

    :param mime_type: String with the type of message sent {image, pdf, plain, etc..}
    :type mime_type: str or None
    :param file_base64: File encoded in base64.
    :type file_base64: str or None

    :return: True if contains and image, false if not
    :rtype: bool
    """
    return bool(mime_type and mime_type.startswith("image/") and file_base64)


def is_quota_error(error: Exception) -> bool:
    """
    Helper function that evaluate if the error is related to a quota limit error 

    :param error: Error generated by the LLM
    :type error: Exception

    :return: True if contains a quota error keyword, False if not
    :rtype: bool
    """
    error_text = str(error).lower()
    return "429" in error_text or "quota" in error_text or "rate limit" in error_text


def analyze_rqt_graph_image(api_key: str, caption: str, mime_type: str, file_base64: str) -> str:
    """
    Analyze the image sent if it is an rqt_graph, and what connections and logic is inside

    :param api_key: API key to create a request for the LLM
    :type api_key: str
    :param caption: User message attached with the image
    :type caption: str
    :param mime_type: String with the type of message sent {image, pdf, plain, etc..}
    :type mime_type: str
    :param file_base64: File encoded in base64.
    :type file_base64: str

    :return: Return the LLM interpretation of the rqt_grap, or a message in case it could analyze the
    image or the quota limit is out
    :rtype: str
    """
    configure = getattr(genai, "configure")
    generative_model = getattr(genai, "GenerativeModel")

    configure(api_key=api_key)
    model_candidates = [
        model_name.strip()
        for model_name in os.getenv(
            "ROSLINE_IMAGE_MODELS",
            "gemini-2.5-flash,gemini-3.0-Flash",
        ).split(",")
        if model_name.strip()
    ]

    prompt = (
        "Analiza esta imagen como si fuera una captura de rqt_graph de ROS 2. "
        "Identifica los nodos visibles, los tópicos, quién publica y quién suscribe, "
        "y resume la arquitectura general del grafo. "
        "Si detectas relaciones que sugieran un flujo de datos importante, explícalas. "
        "Si la imagen no parece ser un rqt_graph, dilo claramente y describe lo que sí ves. "
        "Responde en español, sin Markdown, con frases breves y concretas."
    )

    if caption:
        prompt += f"\n\nContexto adicional del usuario: {caption}"

    image_bytes = base64.b64decode(file_base64)
    last_error: Exception | None = None

    for model_name in model_candidates:
        try:
            model = generative_model(model_name)
            response = model.generate_content(
                [
                    prompt,
                    {"mime_type": mime_type, "data": image_bytes},
                ]
            )

            reply = (getattr(response, "text", "") or "").strip()
            if reply:
                return reply
        except Exception as error:
            last_error = error
            if not is_quota_error(error):
                raise

    if last_error is not None and is_quota_error(last_error):
        return (
            "No pude analizar la imagen porque se agotó la cuota del modelo de visión. "
            "Prueba de nuevo en unos minutos o cambia la variable ROSLINE_IMAGE_MODELS para usar otro modelo."
        )

    return "No pude interpretar la imagen adjunta. Si quieres, reenvíala con más resolución o una captura más centrada del rqt_graph."
